### ISSUE TITLE
Editing captured responses

### ISSUE THREAD

**Issue by lingram-rmn** [ravinet/mahimahi#107]
Howdy, I am interested in using Mahimahi for performance experimentation. For example, I would like to load a page in RecordShell and then edit the HTML response to add [DNS prefetch directives](https://www.chromium.org/developers/design-documents/dns-prefetching).

So, first, does this make sense to do with Mahimahi? Have I missed something that will prevent this from working?

Next, I'm planning to use https://github.com/ravinet/mahimahi/blob/master/src/protobufs/http_record.proto to build a tool to read the request/response record for the document and then write the edited version back (with the relevant headers fixed up). Does that seem like a reasonable way to approach this problem?

**Comment by worenga** [comment]
Your approach sounds logical. 

However, you might want to consider that mahimahi does not parses the http body. That means you will first have to take care of things like compression, chunked encoding etc. before you can get access to the original html. Also you'll need to reverse everything to save it, which could be a lot of work.

Depending on your use case, you might want into mitmproxy. They actually allow to record and replay aswell traffic and expose a python scripting interface to modify responses.

**Comment by lingram-rmn** [comment]
> However, you might want to consider that mahimahi does not parses the http body. That means you will first have to take care of things like compression, chunked encoding etc. before you can get access to the original html. Also you'll need to reverse everything to save it, which could be a lot of work.

Ah, I hadn't considered that. I'll think about how to use mitmproxy. Thanks!
