### ISSUE TITLE
When i use mahimahi CLI mm-delay，my local server stop to work,how to solve the problem

### ISSUE THREAD

**Issue by lixiaoming0017** [ravinet/mahimahi#113]
I am a student from Communication University of China , I have a problem when i use mahimahi, there is a localserver in my computer ,the server's address is http://localhost:8333,  when i use the mahimahi to simulate the network with mm-delay 40 ,my localserver stop working, and the google chrome just show "can not connect the server",but when i stop the mm-delay，the server start work again ,and the google chrome show the response word, how can i solve the problem.Thank you very much

**Comment by keithw** [comment]
`localhost' refers to the IP address of the local interface -- and from inside a container, local really means "local" (still inside the container). This is not where your webserver is running.

You can use the $MAHIMAHI_BASE environment variable to refer to the local interface of the "main" container on your computer, outside the mahimahi container. This is probably what the webserver is listening to.
