### ISSUE TITLE
IPs of nested containers are unreachable

### ISSUE THREAD

**Issue by arslnjmn** [ravinet/mahimahi#119]
1. When I have just one mahimahi container (e.g. by just using mm-delay 20), I am assigned inet 100.64.0.2 and P-t-p 100.64.0.1. From some other shell (i.e. outside the container), I can ping 100.64.0.2 (which incurs an RTT of 40ms) and 100.64.0.1.

2. When I have 2 mahimahi containers chained together (e.g. mm-delay 20 mm-loss downlink 0.1), I am assigned inet 100.64.0.4 and P-t-p 100.64.0.3 within the inner container. From some other shell (i.e. outside both the containers), I cannot ping any of 100.64.0.3/4 but I can still ping 100.64.0.2 (i.e the outermost container - mm-delay 20) and 100.64.0.1.

Both setups shows $MAHIMAHI_BASE is set to 100.64.0.1.

**Problem:** I want to place a webserver inside mahimahi containers. If I just use 1 container, it is reachable. If I chain 2 containers together and start the server within the innermost container, it becomes unreachable.

Is there a fix or workaround that will solve my problem?

**Comment by keithw** [comment]
Each container is inside a NAT relative to its parent, so you will have the same problems you normally do when running a server inside a NAT. The easiest approach is to run the server outside the containers, and run the client inside the innermost one (opening a connection to $MAHIMAHI_BASE). If this doesn't work for you, can you tell us more about your use case? Thanks, Keith

**Comment by keithw** [comment]
You can set up port forwarding yourself with iptables, but we don't (currently) have code to do it automatically.

**Comment by arslnjmn** [comment]
Great. I'll try that.

**Comment by wesmwoo** [comment]
Hi @a-jumani, I'm looking to set up a server inside a mm shell (mm-webreplay) as well. I don't have a ton of experience with iptables and ip routing -- would it be possible for you to share the list of commands you used to configure the forwarding?
