### ISSUE TITLE
No ppa for Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by goelayu** [ravinet/mahimahi#123]
There is no release file for 18.04 LTS ubuntu. 
https://launchpad.net/~keithw/+archive/ubuntu/mahimahi

Can this kindly be added asap.

**Comment by keithw** [comment]
We can do this, but please note that mahimahi 0.98 is in Ubuntu 18.04 LTS already. Why do you need it added to the PPA?

**Comment by goelayu** [comment]
Sometimes installing using the packet manager is easier, specially on a new machine. 
Installing using the source works fine, but requires manually installing all the transitive dependencies.

**Comment by keithw** [comment]
Hello -- mahimahi is **in** Ubuntu 18.04 LTS (universe). You can just run `sudo apt install mahimahi` out of the box and it will install the package. You do not need to add a PPA.
