### ISSUE TITLE
Why the xcb_get_setup return the null pointer

### ISSUE THREAD

**Issue by bupt-steven** [ravinet/mahimahi#126]
### mm-delay 100 mm-link  /home/netlab/TCPgame/180917/env/ATT-LTE-driving.down /home/netlab/TCPgame/180917/env/ATT-LTE-driving.down --meter-downlink --downlink-queue=droptail --downlink-queue-args=packets=140 -- sh -c 'python /home/netlab/TCPgame/180917/env/run_receiver.py $MAHIMAHI_BASE 57083'

Died on std::runtime_error: xcb_get_setup: returned null pointer
Died on std::runtime_error: `downlink': process exited with failure status 1
Died on std::runtime_error: `mm-link /home/netlab/TCPgame/180917/env/ATT-LTE-driving.down /home/netlab/TCPgame/180917/env/ATT-LTE-driving.down --meter-downlink --downlink-queue=droptail --downlink-queue-args=packets=140 -- sh -c python /home/netlab/TCPgame/180917/env/run_receiver.py $MAHIMAHI_BASE 57083': process exited with failure status 1
Died on std::runtime_error: `packetshell': process exited with failure status 1

**Comment by keithw** [comment]
This indicates an X11 error (xcb_get_setup: returned null pointer) trying to launch the downlink meter you requested (`--meter-downlink`).

What is your DISPLAY environment variable? Can `xlogo` successfully pop up a window?

**Comment by bupt-steven** [comment]
Thanks, I know what happened.

**Comment by miqianmimi** [comment]
may any tell me i already installed mahimahi ,but when i use "
mm-delay 20 mm-link --meter-all /usr/share/mahimahi/traces/Verizon-LTE-short.up /usr/share/mahimahi/traces/Verizon-LTE-short.down" 
and i got error >Died on std::runtime_error: xcb_get_setup: returned null pointer
Died on std::runtime_error: xcb_get_setup: returned null pointer
Died on std::runtime_error: `downlink': process exited with failure status 1
Died on std::runtime_error: `mm-link --meter-all /usr/share/mahimahi/traces/Verizon-LTE-short.up /usr/share/mahimahi/traces/Verizon-LTE-short.down': process exited with failure status 1
Died on std::runtime_error: `packetshell': process exited with failure status 1
i don't know why .

**Comment by keithw** [comment]
This indicates an X11 error (xcb_get_setup: returned null pointer) trying to launch the visual meters you requested (--meter-all).

What is your DISPLAY environment variable? Can xlogo successfully pop up a window?

**Comment by miqianmimi** [comment]
DISPLAY=localhost:10.0 and xlogo can not pop up a window.
```shell
Error: Can't open display: localhost:10.0
```
so how can i fix it ??

**Comment by keithw** [comment]
If you want the live animated meter, you'll have to get X working. The problem seems to be unrelated to mahimahi. `localhost:10.0` suggests you logged in with `ssh -X` or something and are trying to forward X over the connection, which you also probably don't want to do (because the animation would consume a lot of throughput). You'll have the best results if you use the computer normally (on a graphical consume/monitor) instead of over an SSH connection.

Or you can just run mm-link without the `--meter-all` option and then you won't get the animation and it won't try to use a graphical display or X11 at all.

**Comment by miqianmimi** [comment]
hello , i find i am just running your another repo 's './run-contest [username]'  but got some problem .
```shell
1terminate called after throwing an instance of 'unix_error'
  what():  socket: Address family not supported by protocol
terminate called after throwing an instance of 'unix_error'
  what():  socket: Address family not supported by protocol
Died on std::runtime_error: `bash -c ./sender $MAHIMAHI_BASE 9090': process died on signal 6
Died on std::runtime_error: `packetshell': process exited with failure status 1
Died on std::runtime_error: `mm-link /usr/bin/../share/mahimahi/traces/Verizon-LTE-short.down /usr/bin/../share/mahimahi/traces/Verizon-LTE-short.up --meter-uplink --meter-uplink-delay --once --uplink-log=/tmp/contest_uplink_log -- bash -c ./sender $MAHIMAHI_BASE 9090': process exited with failure status 1
Died on std::runtime_error: `packetshell': process exited with failure status 1

Use of uninitialized value $arrival_sum in division (/) at /usr/bin/mm-throughput-graph line 149, <> line 158.
Use of uninitialized value $departure_sum in division (/) at /usr/bin/mm-throughput-graph line 150, <> line 158.
Must have at least one departure event at /usr/bin/mm-throughput-graph line 153, <> line 158.
mm-throughput-graph exited with error. NOT uploading at ./run-contest line 55.
```
is there any problem with my env??
or is this a problem of Mahimahi.
thank you so much

**Comment by miqianmimi** [comment]
thank you !  I know what happened.

**Comment by hexi519** [comment]
> If you want the live animated meter, you'll have to get X working. The problem seems to be unrelated to mahimahi. `localhost:10.0` suggests you logged in with `ssh -X` or something and are trying to forward X over the connection, which you also probably don't want to do (because the animation would consume a lot of throughput). You'll have the best results if you use the computer normally (on a graphical consume/monitor) instead of over an SSH connection.
> 
> Or you can just run mm-link without the `--meter-all` option and then you won't get the animation and it won't try to use a graphical display or X11 at all.

Hi~ Xlogo can pop up and DISPLAY is localhost:12.0, so what should I do to fix it up ？
