### ISSUE TITLE
Chrome process opened inside a mahimahi replay shell doesn't accept keyboard input. 

### ISSUE THREAD

**Issue by ayushgoel1610** [ravinet/mahimahi#127]
I've lately been experiencing this issue when I launch a chromium browser instance inside the mahimahi replay shell, the chromium browser won't acknowledge my keyboard key strokes. 
The chromium process logs an IBUS warning every time I press a key on my keyboard which says "Warning: Events Queue growing too big, will start to drop"

I am using the latest version of mahimahi and tested on varying versions of chrome (65, 68).

**Comment by keithw** [comment]
Hi -- I was not able to replicate this (in Chromium 69.0.3497.81 on Ubuntu 18.04 LTS). Could you please provide more details about how to replicate the problem? Have you tried running Chromium as described in the mahimahi(1) man page (with a `--user-data-dir=/tmp/nonexistent$(date +%s%N)` flag to make sure it starts a new process inside the mahimahi container)?

You may need to end up filing a bug with Chromium...

**Comment by ayushgoel1610** [comment]
The bug was related to the way IBUS works. The IBUS tmp folder was running out of space for some reason, simple had to delete it. 

Closing this. Thanks.
