### ISSUE TITLE
Is there a way binding mahimahi to real nic not a virtual?

### ISSUE THREAD

**Issue by wen-zheng** [ravinet/mahimahi#139]

**Comment by wen-zheng** [comment]
can I using mahimahi like tc or netem in linux?

**Comment by keithw** [comment]
The mahimahi link emulators (mm-delay, mm-link, mm-loss, mm-onoff) create a new network namespace (a container) that is connected to the outside one via a pair of TUN devices (one inside the container, one outside). The modeled effect (loss, variable bottleneck with some queue discipline, etc.) occurs between that pair of TUN devices, i.e., for any packet entering or leavin the container.

Any packet that comes out of the container is subject to a NAT rule to let it talk outside. So any program you run inside the container can talk over the Internet, including over a real NIC. So the answer to your question is sort of "yes". But the link effects are always applied between a pair of TUN devices.

**Comment by wen-zheng** [comment]
Thanks
