### ISSUE TITLE
where can I find manual pages ？

### ISSUE THREAD

**Issue by z6833** [ravinet/mahimahi#140]
Hi,
The manual you mentioned [http://mahimahi.mit.edu/](http://mahimahi.mit.edu/) here can not be found . The link `mahimahi(1)` is none . Where can I find the using guidebooks ？

**Comment by keithw** [comment]
"mahimahi(1)" refers to the Unix manual page for mahimahi -- after installing the software, run "man mahimahi" or "man 1 mahimahi" to read it.
