### ISSUE TITLE
Can't work in a docker container.

### ISSUE THREAD

**Issue by yhcchaos** [ravinet/mahimahi#153]
Hello!
An error exists when I run mm-delay in a docker container.Below is the ouput of ubuntu18.04.

Died on unix_error: ioctl delay-19918: Operation not permitted.

Thanks very much if you can help me with this problem.

**Comment by keithw** [comment]
I understand people have been able to get this to work; you'll have to configure Docker to allow the creation of network namespaces inside the container.

**Comment by yhcchaos** [comment]
ok, thanks.
