### ISSUE TITLE
"make" commad occurs "read: Input/output error" when installing Mahimahi

### ISSUE THREAD

**Issue by INF0x3f3f3f3f** [ravinet/mahimahi#154]
I am sorry to bother you.
When I install MahiMahi, I follow the steps below(https://github.com/Soheil-ab/Orca).

`sudo apt-get install build-essential git debhelper autotools-dev dh-autoreconf iptables protobuf-compiler libprotobuf-dev pkg-config libssl-dev dnsmasq-base ssl-cert libxcb-present-dev libcairo2-dev libpango1.0-dev iproute2 apache2-dev apache2-bin iptables dnsmasq-base gnuplot iproute2 apache2-api-20120211 libwww-perl
git clone https://github.com/ravinet/mahimahi 
cd mahimahi
./autogen.sh
./configure
make`

However, after entering the "make" command, the following error occurs:

`/bin/bash ../../libtool  --tag=CXX   --mode=link g++ -pedantic -Wall -Wextra -Weffc++ -Werror -g -O2 -pthread  -o mm-link linkshell.o link_queue.o -lrt ../util/libutil.a ../packet/libpacket.a ../graphing/libgraph.a -lxcb-present -lxcb -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo 
libtool: link: g++ -pedantic -Wall -Wextra -Weffc++ -Werror -g -O2 -pthread -o mm-link linkshell.o link_queue.o  -lrt ../util/libutil.a ../packet/libpacket.a ../graphing/libgraph.a -lxcb-present -lxcb -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo -pthread
/usr/bin/ld: error: /lib/x86_64-linux-gnu/libX11.so.6: read: Input/output error
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:621: mm-link] Error 1
make[3]: Leaving directory '/home/wyk/mahimahi/src/frontend'
make[2]: *** [Makefile:378: all-recursive] Error 1
make[2]: Leaving directory '/home/wyk/mahimahi/src'
make[1]: *** [Makefile:424: all-recursive] Error 1
make[1]: Leaving directory '/home/wyk/mahimahi'
make: *** [Makefile:356: all] Error 2`

How to solve that? Could you give me some instructions or advice? Thank you!
I am looking forward to your reply.

**Comment by keithw** [comment]
I'm afraid this is probably a problem with your computer and unrelated to mahimahi. Do you get this error if you run any program that tries to read the "/lib/x86_64-linux-gnu/libX11.so.6" file? (E.g. try running "sha1sum /lib/x86_64-linux-gnu/libX11.so.6" at the command line.) Sorry I couldn't be more helpful.
