### ISSUE TITLE
error occurs when using "make" command

### ISSUE THREAD

**Issue by myrealMVP** [ravinet/mahimahi#155]
Hi. Thank you very much for your contribution to the community.

I use Ubuntu and the version shows below.
![image](https://user-images.githubusercontent.com/84263746/184467385-f7914adb-cb72-4c41-be6b-748024f60cc5.png)

I installed the mahimahi this morning. However, when I used "make" command, the following error occurs.
![image](https://user-images.githubusercontent.com/84263746/184467338-f32d4a8e-5b48-4b70-a94b-c0206b45a4e4.png)

Could you give me some advice? Thank you!

**Comment by devmrfitz** [comment]
+1
This happened with me too

**Comment by chenxi-yang** [comment]
+1 any solution?

**Comment by superlitong** [comment]
Maybe you can simply run the following instead: sudo apt-get install mahimahi

**Comment by shane-zhang** [comment]
Ubuntu1804 works.

**Comment by keithw** [comment]
I think this is fixed (for now) in abce65a4c5361230d64e7f04575bced478e1a19f
