### ISSUE TITLE
mahimahi fails to build with GCC 6

### ISSUE THREAD

**Issue by doko42** [ravinet/mahimahi#97]
see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822380 for the first error

> g++ -DHAVE_CONFIG_H -I. -I../..  -std=c++11 -pthread -Wdate-time -D_FORTIFY_SOURCE=2 -pedantic -Wall -Wextra -Weffc++ -Werror -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -c -o poller.o poller.cc
> poller.cc: In member function 'Poller::Result Poller::poll(const int&)':
> poller.cc:40:80: error: 'accumulate' was not declared in this scope
>                           [] ( bool acc, pollfd x ) { return acc or x.events; } ) ) {
>                                                                                 ^
> Makefile:438: recipe for target 'poller.o' failed
> make[4]: *** [poller.o] Error 1
> make[4]: Leaving directory '/<<PKGBUILDDIR>>/src/util'
> Makefile:376: recipe for target 'all-recursive' failed

**Comment by keithw** [comment]
Fixed by d1b0c64b6d5c71253ff34d5d2161736f86624b45
